---
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "8883:8883"
  timescale:
    image: timescale/timescaledb:latest-pg17
    container_name: timescale
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-yourusername}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yourpassword}
      - POSTGRES_DB=${POSTGRES_DB:-yourdatabase}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - POSTGRES_HOST=timescale
      - POSTGRES_DB=${POSTGRES_DB:-yourdatabase}
      - POSTGRES_USER=${POSTGRES_USER:-yourusername}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yourpassword}
      - MQTT_BROKER_URL=mosquitto
      - MQTT_CLIENT_ID=grafana_client
      - MQTT_USERNAME=${MQTT_USERNAME:-your_mqtt_username}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-your_mqtt_password}
      - MQTT_PORT=1883
      # Alert thresholds - adjust based on crop requirements
      - ALERT_TEMP_HIGH=${ALERT_TEMP_HIGH:-28}
      - ALERT_TEMP_LOW=${ALERT_TEMP_LOW:-18}
      - ALERT_HUMIDITY_HIGH=${ALERT_HUMIDITY_HIGH:-70}
      - ALERT_HUMIDITY_LOW=${ALERT_HUMIDITY_LOW:-40}
      - ALERT_LIGHTS_ON_HOUR=${ALERT_LIGHTS_ON_HOUR:-06}
      - ALERT_LIGHTS_OFF_HOUR=${ALERT_LIGHTS_OFF_HOUR:-22}
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/alerting:/etc/grafana/provisioning/alerting
    depends_on:
      - timescale
      - mosquitto
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - timescale
      - mosquitto
    environment:
      - POSTGRES_HOST=timescale
      - POSTGRES_DB=${POSTGRES_DB:-yourdatabase}
      - POSTGRES_USER=${POSTGRES_USER:-yourusername}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yourpassword}
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
